---
- name: if singularity version is not defined, define the default
  set_fact:
    singularity_version: "{{ singularity_version | default(singularity_default_version) }}"

- name: Check singularity version
  shell:
    cmd: "{{ 
      'singularity version' 
      if singularity_version is version('3.0', operator='ge') 
      else 'singularity --version' }}"
    strip_empty_ends: true
  register: singularity_version_check
  # When the command is not found, stdout will be empty (message in stderr)
  # The correct version installed check will thus return false
  failed_when: false
  changed_when: false

- name: Check if correct version is installed
  set_fact:
    singularity_installed: "{{ singularity_version_check.stdout == singularity_version }}"

- name: if singularity_version is pre-3.0
  include: singularity-pre-3.yml
  when: singularity_version is version('3.0', operator='lt') and not singularity_installed

- name: if singularity_version is 3.0 or later
  include: singularity-post-3.yml
  when: singularity_version is version('3.0', operator='ge') and not singularity_installed
