---
- name: if singularity_version is pre-3.0
  include: singularity-pre-3.yml
  when: singularity_version is not defined or singularity_version == "" or singularity_version is version('3.0', operator='lt')

- name: if singularity_version is 3.0 or later
  include: singularity-post-3.yml
  when: singularity_version is defined and singularity_version != "" and singularity_version is version('3.0', operator='ge')
