---
# tasks file for ansible-singularity
- name: Ubuntu package installation for v3.0 or newer
  apt:
    name: 
      - build-essential
      - libssl-dev
      - uuid-dev
      - squashfs-tools
      - libseccomp-dev
      - wget
      - pkg-config
      - git
      - cryptsetup
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: CentOS package installation for v3.0 or newer
  yum:
    name: 
      - "@Development Tools"
      - openssl-devel
      - libuuid-devel
      - squashfs-tools
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: download the singularity release
  get_url:
    url: "https://github.com/sylabs/singularity/releases/download/v{{singularity_version}}/singularity-{{singularity_version}}.tar.gz"
    dest: "/tmp/singularity-{{singularity_version}}.tar.gz"
    mode: 0644

- name: untar the singularity archive
  unarchive:
    src: "/tmp/singularity-{{singularity_version}}.tar.gz" 
    dest: "/opt/singularity-{{singularity_version}}"
    #    extra_opts: [--strip-components=1]
    #    remote_src: yes


- name: execute mconfig for v3.0 or newer
  shell: ./mconfig chdir="/opt/singularity-{{singularity_version}}"

- name: execute make build for v3.0 or newer
  shell: make -C builddir chdir="/opt/singularity-{{singularity_version}}"

- name: execute make install for v3.0 or newer
  shell: make -C builddir install chdir="/opt/singularity-{{singularity_version}}"
