---
# tasks file for ansible-singularity
- name: Ubuntu package installation for v3.0 or newer
  apt:
    name: 
      - build-essential
      - libssl-dev
      - uuid-dev
      - squashfs-tools
      - libseccomp-dev
      - wget
      - pkg-config
      - git
      - cryptsetup
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: CentOS package installation for v3.0 or newer
  yum:
    name: 
      - "@Development Tools"
      - openssl-devel
      - libuuid-devel
      - squashfs-tools
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: create variable that points to sylabs build directory
  set_fact: singularity_build_dir="{{singularity_go_path}}/src/github.com/sylabs"

- name: create the go path directory
  file:
    path: "{{singularity_build_dir}}"
    state: directory
    mode: 0755

- name: clone the singularity repo for v3.0 or newer
  git:
    repo: "https://github.com/singularityware/singularity.git"
    dest: "{{singularity_build_dir}}/singularity"
    version: "v{{ singularity_version }}"

- name: get dependencies for v3.0 or newer
  shell: go get -u -v github.com/golang/dep/cmd/dep chdir="{{singularity_build_dir}}/singularity"
  environment:
    GOPATH: "{{singularity_go_path}}"
    PATH: "{{singularity_go_path}}/bin:/usr/local/bin:{{ansible_env.PATH}}"

- name: execute mconfig for v3.0 or newer
  shell: ./mconfig chdir="{{singularity_build_dir}}/singularity"
  environment:
    GOPATH: "{{singularity_go_path}}"
    PATH: "{{singularity_go_path}}/bin:/usr/local/bin:{{ansible_env.PATH}}"

- name: execute make build for v3.0 or newer
  shell: make -C builddir chdir="{{singularity_build_dir}}/singularity"
  environment:
    GOPATH: "{{singularity_go_path}}"
    PATH: "{{singularity_go_path}}/bin:/usr/local/bin:{{ansible_env.PATH}}"

- name: execute make install for v3.0 or newer
  shell: make -C builddir install chdir="{{singularity_build_dir}}/singularity"
  environment:
    GOPATH: "{{singularity_go_path}}"
    PATH: "{{singularity_go_path}}/bin:/usr/local/bin:{{ansible_env.PATH}}"
